feat: 优化关键词排序算法
surgioproject/surgio pull request #163
Opened 2021-12-01 06:16 UTC by baranwang

增加排序评分

2021-12-09 03:57 UTC, baranwang commented
ping @geekdada

2021-12-09 09:13 UTC, geekdada commented
感谢贡献代码！

稍后有空时 review。

2021-12-10 22:52 UTC, geekdada commented
请问有没有空更新一下文档？

2021-12-11 11:16 UTC, geekdada commented
请检查一下测试用例，没有通过

2021-12-11 11:59 UTC, baranwang commented
> 请检查一下测试用例，没有通过

我看了一下，测试用例master分支也是跑不通的… 好像不是这个pr的问题哎～

2021-12-11 14:46 UTC, geekdada commented
覆盖率那个可以暂时忽略，其他的是可以通过的。

2021-12-11 15:21 UTC, baranwang commented
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/11427801/145681826-d590124c-c48a-4adc-974e-a3b69111fd8c.png">
哦？我这边测试master和我pr的分支报错是一样的

2021-12-11 16:11 UTC, geekdada commented
我在本地和 CI 都跑了 master 分支，是没问题的。

2021-12-17 19:31 UTC, geekdada commented
请问怎么样了呢

2021-12-20 03:22 UTC, baranwang commented
master上单元测试同样过不了啊，没有找到问题的点🙃

2021-12-20 08:21 UTC, geekdada commented
等我今天checkout你的分支看一下。

2021-12-23 21:03 UTC, geekdada requested changes
为了确保稳定，还请增加新用法的单测，感谢！

2021-12-23 21:03 UTC, geekdada commented on docs/guide/advance/custom-filter.md
> +    preferNodes: utils.useSortedKeywords([
这里应该是这样吧

```
utils.useSortedKeywords(
  ['HC', 'AIA', 'IEPL'],
  ['香港', '台湾', '新加坡', '日本'],
)
```

2021-12-23 21:03 UTC, geekdada commented on lib/utils/filter.ts
> +  ...subKeywords: string[][]
这里为什么不写成 `subKeywords?: string[]`

2021-12-23 21:03 UTC, geekdada commented on lib/utils/filter.ts
> +    return _.sortBy(nodeList, (node) => {
单测挂掉是因为原本的 `filter` 在新的实现里变成了 `sort`

2023-09-21 08:19 UTC, closed without merging